## Server Configuration
SERVER_NAME: "codebase-go-rest-lite"
SERVER_IP: "127.0.0.1"
SERVER_PORT: "3000"
SERVER_STORE_PATH: "./misc/stores"
SERVER_UPLOAD_PATH: "./misc/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "debug"

## Router Configuration
ROUTER_BASE_PATH: ""

## Cryptography Configuration
CRYPT_PRIVATE_KEY_FILE: "./misc/private.key"
CRYPT_PUBLIC_KEY_FILE: "./misc/public.key"
